declare const styles: {
  readonly "chartItemDeleteButton": string;
  readonly "chartItemDeleteButtonWrap": string;
  readonly "chartItemInput": string;
  readonly "chartItemInputField": string;
  readonly "colorChip": string;
  readonly "colorColumn": string;
  readonly "colorGrid": string;
  readonly "colorHex": string;
  readonly "colorSwatch": string;
  readonly "configValueList": string;
  readonly "configValueRow": string;
  readonly "divider": string;
  readonly "field-label": string;
  readonly "field-row": string;
  readonly "fieldLabel": string;
  readonly "fieldRow": string;
  readonly "horizontalBarActions": string;
  readonly "horizontalBarBackButton": string;
  readonly "horizontalBarControls": string;
  readonly "horizontalBarHeader": string;
  readonly "horizontalBarLeftPanel": string;
  readonly "horizontalBarPage": string;
  readonly "horizontalBarPreviewPanel": string;
  readonly "horizontalBarRightPanel": string;
  readonly "horizontalBarTypeTitle": string;
  readonly "navBackButton": string;
  readonly "navTitle": string;
  readonly "section-title": string;
  readonly "sectionTitle": string;
  readonly "tokenName": string;
  readonly "typographyTokenList": string;
  readonly "typographyTokenRow": string;
  readonly "typographyTokenValue": string;
  readonly "variableKey": string;
};
export = styles;

